'use server'

import { Course } from '@/types/course'

export async function fetchCourses(): Promise<Course[]> {
  // Simulation d'un appel API ou récupération depuis une base de données
  // Dans un vrai projet, cela pourrait être un appel à une API externe
  
  return [
    {
      id: 1,
      title: 'CompTIA Security+ 701 Training | CompTIA Security+ Certification',
      description: 'Master modern web development from scratch. Learn HTML, CSS, JavaScript, React, Node.js, MongoDB, and deploy real-world projects.',
      duration: '10 heures',
      level: 'Intermediate',
      instructor: 'John Doe',
      price: 99,
      thumbnail: '/assets/react-course.jpg',
      backgroundImage: '/images/Container.png',
      bestSeller: true,
      category: 'Web Development',
      status: 'Enrolling Now',
      rating: 4.8,
      reviews: 2847,
      students: 12458,
      certificateIncluded: true,
    },
    {
      id: 2,
      title: 'GRAPHIC DESIGN MASTERCLASS - LEARN GREAT DESIGN',
      description: 'Learn the fundamentals of graphic design and create stunning visual designs. Master tools like Photoshop, Illustrator, and InDesign.',
      duration: '15 heures',
      level: 'Intermediate',
      instructor: 'Jane Smith',
      price: 149,
      thumbnail: '/assets/graphic-design.jpg',
      backgroundImage: '/images/Container.png',
      bestSeller: false,
      category: 'Design',
      status: 'Enrolling Now',
      rating: 4.9,
      reviews: 1200,
      students: 8500,
      certificateIncluded: true,
    },
    {
      id: 3,
      title: 'THE COMPLETE DIGITAL MARKETING COURSE - 12 COURSES IN 1',
      description: 'Master digital marketing strategies including SEO, social media marketing, email marketing, and Google Ads.',
      duration: '20 heures',
      level: 'Beginner',
      instructor: 'Bob Johnson',
      price: 199,
      thumbnail: '/assets/digital-marketing.jpg',
      backgroundImage: '/images/Container.png',
      bestSeller: true,
      category: 'Marketing',
      status: 'Enrolling Now',
      rating: 4.7,
      reviews: 950,
      students: 6200,
      certificateIncluded: true,
    },
    {
      id: 4,
      title: 'PHOTOGRAPHY ON CAMERAS AND PHONES FOR BEGINNERS',
      description: 'Learn photography fundamentals and take stunning photos with both professional cameras and smartphones.',
      duration: '12 heures',
      level: 'Beginner',
      instructor: 'Sarah Williams',
      price: 79,
      thumbnail: '/assets/photography.jpg',
      backgroundImage: '/images/Container.png',
      bestSeller: false,
      category: 'Photography',
      status: 'Enrolling Now',
      rating: 4.6,
      reviews: 750,
      students: 4500,
      certificateIncluded: true,
    },
    {
      id: 5,
      title: 'PYTHON FOR DATA SCIENCE AND MACHINE LEARNING',
      description: 'Learn Python programming for data science, machine learning, and artificial intelligence. Build real-world projects.',
      duration: '25 heures',
      level: 'Intermediate',
      instructor: 'Michael Chen',
      price: 179,
      thumbnail: '/assets/python-course.jpg',
      backgroundImage: '/images/Container.png',
      bestSeller: true,
      category: 'Programming',
      status: 'Enrolling Now',
      rating: 4.9,
      reviews: 2100,
      students: 15200,
      certificateIncluded: true,
    },
    {
      id: 6,
      title: 'INSTAGRAM MARKETING 2024: COMPLETE GUIDE TO INSTAGRAM GROWTH',
      description: 'Master Instagram marketing strategies to grow your followers, increase engagement, and drive sales.',
      duration: '8 heures',
      level: 'Beginner',
      instructor: 'Emily Davis',
      price: 89,
      thumbnail: '/assets/instagram-marketing.jpg',
      backgroundImage: '/images/Container.png',
      bestSeller: false,
      category: 'Marketing',
      status: 'Enrolling Now',
      rating: 4.5,
      reviews: 650,
      students: 3800,
      certificateIncluded: true,
    },
  ]
}
